repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]

  -   repo: https://github.com/fsouza/autoflake8
      rev: v0.4.0
      hooks:
      -   id: autoflake8

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]

  # - repo: https://github.com/pycqa/flake8
  #   rev: 4.0.1
  #   hooks:
  #     - id: flake8
  #       additional_dependencies:
  #         - flake8-bugbear
  #         - flake8-comprehensions
  #         - flake8-simplify

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.3.0
  #   hooks:
  #     - id: mypy
  #       args: [--explicit-package-bases]
  #       additional_dependencies:
  #         - types-dataclasses >= 0.1.3
  #         - types-PyYAML
  #         - tomli >= 0.2.6, < 2.0.0
  #         - types-typed-ast >= 1.4.1
  #         - click >= 8.1.0
  #         - packaging >= 22.0
  #         - platformdirs >= 2.1.0
  #         - pytest
  #         - hypothesis
